name: Build and push
on:
  push:
    branches:
    - master

jobs:
  buildpushtag:
    name: build and push
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: docker login
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_HOST }}
        username:     ${{ secrets.ACR_PUSH_USER }}
        password:     ${{ secrets.ACR_PUSH_PASSWORD }}

    - name: build and push
      env:
        IMAGE_NAME: ${{ secrets.ACR_HOST }}/padoa/odfe-cli-monitoring
      run: |-
        docker build -t "${IMAGE_NAME}:${GITHUB_SHA}" .
        docker push "${IMAGE_NAME}:${GITHUB_SHA}"
